
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwMDUzNTkx","is_bot":false,"login":"ChrisWoolson","name":"Chris Woolson"},"headRefName":"CW-addGetRecommendationRequest","number":52,"title":"Cw-add get recommendation request","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/52"},{"author":{"id":"MDQ6VXNlcjMwMDUzNTkx","is_bot":false,"login":"ChrisWoolson","name":"Chris Woolson"},"headRefName":"CW-RecReqController","number":51,"title":"Reccomendation Request Controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/51"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Articles-Controller","number":49,"title":"Justin articles controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/49"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"ArticlesDB","number":48,"title":"Database table created for Articles","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/48"},{"author":{"id":"U_kgDOB3BkNQ","is_bot":false,"login":"TantaiYanhen","name":"Sam Bian"},"headRefName":"Sam-HelpRequest-Delete","number":47,"title":"Add DELETE endpoint for a specific record in HelpRequest table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/47"},{"author":{"id":"U_kgDOB3BkNQ","is_bot":false,"login":"TantaiYanhen","name":"Sam Bian"},"headRefName":"Sam-HelpRequest-Put","number":46,"title":"Add PUT endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/46"},{"author":{"id":"U_kgDOB3BkNQ","is_bot":false,"login":"TantaiYanhen","name":"Sam Bian"},"headRefName":"Sam-HelpRequest-Get","number":45,"title":"Add GET endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/45"},{"author":{"id":"U_kgDOB3BkNQ","is_bot":false,"login":"TantaiYanhen","name":"Sam Bian"},"headRefName":"Sam-HelpRequest-controller","number":44,"title":"Create HelpRequestController, add GET all and POST ","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/44"},{"author":{"id":"U_kgDOB3BkNQ","is_bot":false,"login":"TantaiYanhen","name":"Sam Bian"},"headRefName":"Sam-HelpRequest-create-db","number":43,"title":"Create Database Table for HelpRequest","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/43"}]
