
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXkTqQ","is_bot":false,"login":"El-Beetor","name":"Victor Garcia"},"headRefName":"Victor-MenuItem-create-db","number":61,"title":"Created database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/61"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Articles-Controller","number":49,"title":"Justin articles controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/49"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"ArticlesDB","number":48,"title":"Database table created for Articles","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/48"}]
