
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-1
pull_requests: [{"author":{"id":"U_kgDOBXrZiw","is_bot":false,"login":"Bravo-Luis","name":"Luis Bravo"},"headRefName":"luis-UCSBOrganization-create-db","number":60,"title":"adding UCSBOrganization table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/60"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"Winston-MenuItemReview-Delete","number":59,"title":"Add DELETE endpoint for a specific record in MenuItemReview table.","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/59"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"Winston-MenuItemReview-Put","number":58,"title":"Add PUT (edit) endpoint for a single record in MenuItemReview table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/58"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"Winston-MenuItemReview-Get","number":57,"title":"Add GET (show) endpoint for a single record in MenuItemReview table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/57"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"Winston-MenuItemReview-Controller","number":56,"title":" Create MenuItemReviewController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/56"},{"author":{"id":"U_kgDOBp4StA","is_bot":false,"login":"winzuo","name":""},"headRefName":"Winston-MenuItemReviewTable","number":53,"title":"Create database table for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/53"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"Justin-Articles-Controller","number":49,"title":"Justin articles controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/49"},{"author":{"id":"U_kgDOBs097g","is_bot":false,"login":"haojustin","name":""},"headRefName":"ArticlesDB","number":48,"title":"Database table created for Articles","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-1/pull/48"}]
